import { ExampleDeck } from "./types";
import front from "@/constants/builtInTemplates/front";
import back from "@/constants/builtInTemplates/back";

const deck: ExampleDeck = {
  name: "Charades",
  description:
    "A fun game where players act out a word or phrase without speaking.",
  templates: {
    back: {
      templateId: back.templateId,
      dataTemplateMapping: {
        color: {
          dataId: "color",
          templateDataId: back.schema.color.id,
        },
      },
    },
    front: {
      dataTemplateMapping: {
        title: {
          dataId: "title",
          templateDataId: front.schema.title.id,
        },
        description: {
          dataId: "description",
          templateDataId: front.schema.description.id,
        },
        color: {
          dataId: "color",
          templateDataId: front.schema.color.id,
        },
      },
      templateId: front.templateId,
    },
  },
  dataSchema: {
    description: {
      id: "description",
      type: "text",
      defaultValidatedValue: {
        type: "null",
        value: null,
      },
    },
    color: {
      id: "color",
      type: "color",
      defaultValidatedValue: {
        type: "color",
        value: "#FFDCCC",
      },
    },
  },
  cards: [
    { title: "Elephant" },
    { title: "Cupcake" },
    { title: "Superman" },
    { title: "Pirate" },
    { title: "Tennis" },
    { title: "Karate" },
    { title: "Ballet" },
    { title: "Surfing" },
    { title: "Skiing" },
    { title: "Snowball fight" },
    { title: "Penguin" },
    { title: "Kangaroo" },
    { title: "Doctor" },
    { title: "Firefighter" },
    { title: "Astronaut" },
    { title: "Dinosaur" },
    { title: "Robot" },
    { title: "Lion" },
    { title: "Guitar" },
    { title: "Piano" },
    { title: "Dancing" },
    { title: "Fishing" },
    { title: "Cooking" },
    { title: "Gardening" },
    { title: "Reading" },
    { title: "Writing" },
    { title: "Painting" },
    { title: "Singing" },
    { title: "Cycling" },
    { title: "Running" },
    { title: "Swimming" },
    { title: "Basketball" },
    { title: "Football" },
    { title: "Baseball" },
    { title: "Soccer" },
    { title: "Volleyball" },
    { title: "Hockey" },
    { title: "Golf" },
    { title: "Bowling" },
    { title: "Skateboarding" },
    { title: "Rollerblading" },
    { title: "Ice skating" },
    { title: "Mountain climbing" },
    { title: "Camping" },
    { title: "Hiking" },
    { title: "Bird watching" },
    { title: "Stargazing" },
    { title: "Picnic" },
    { title: "Barbecue" },
    { title: "Shopping" },
    { title: "Traveling" },
    { title: "Flying" },
    { title: "Driving" },
    { title: "Train ride" },
    { title: "Bus ride" },
    { title: "Subway ride" },
    { title: "Taxi ride" },
    { title: "Horseback riding" },
    { title: "Camel ride" },
    { title: "Elephant ride" },
    { title: "Hot air balloon" },
    { title: "Parachuting" },
    { title: "Bungee jumping" },
    { title: "Skydiving" },
    { title: "Scuba diving" },
    { title: "Snorkeling" },
    { title: "Fishing" },
    { title: "Hunting" },
    { title: "Archery" },
    { title: "Shooting" },
    { title: "Laser tag" },
    { title: "Paintball" },
    { title: "Video games" },
    { title: "Board games" },
    { title: "Card games" },
    { title: "Puzzle" },
    { title: "Chess" },
    { title: "Checkers" },
    { title: "Dominoes" },
    { title: "Jenga" },
    { title: "Monopoly" },
    { title: "Scrabble" },
    { title: "Uno" },
    { title: "Poker" },
    { title: "Blackjack" },
    { title: "Roulette" },
    { title: "Slot machine" },
    { title: "Bingo" },
    { title: "Karaoke" },
    { title: "Magic show" },
    { title: "Circus" },
    { title: "Theater" },
    { title: "Movie" },
    { title: "Concert" },
    { title: "Opera" },
    { title: "Ballet" },
    { title: "Musical" },
    { title: "Stand-up comedy" },
    { title: "Talent show" },
    { title: "Fashion show" },
    { title: "Parade" },
    { title: "Festival" },
    { title: "Carnival" },
    { title: "Fair" },
    { title: "Amusement park" },
    { title: "Water park" },
    { title: "Zoo" },
    { title: "Aquarium" },
    { title: "Museum" },
    { title: "Art gallery" },
    { title: "Library" },
    { title: "Bookstore" },
    { title: "Coffee shop" },
    { title: "Restaurant" },
    { title: "Cafe" },
    { title: "Bakery" },
    { title: "Ice cream shop" },
    { title: "Candy store" },
    { title: "Toy store" },
    { title: "Clothing store" },
    { title: "Shoe store" },
    { title: "Jewelry store" },
    { title: "Furniture store" },
    { title: "Electronics store" },
    { title: "Hardware store" },
    { title: "Grocery store" },
    { title: "Supermarket" },
    { title: "Mall" },
    { title: "Market" },
    { title: "Flea market" },
    { title: "Garage sale" },
    { title: "Auction" },
    { title: "Bank" },
    { title: "Post office" },
    { title: "Police station" },
    { title: "Fire station" },
    { title: "Hospital" },
    { title: "Clinic" },
    { title: "Pharmacy" },
    { title: "Dentist" },
    { title: "Veterinarian" },
    { title: "School" },
    { title: "University" },
    { title: "Library" },
    { title: "Office" },
    { title: "Factory" },
    { title: "Warehouse" },
    { title: "Construction site" },
    { title: "Farm" },
    { title: "Ranch" },
    { title: "Orchard" },
    { title: "Vineyard" },
    { title: "Winery" },
    { title: "Brewery" },
    { title: "Distillery" },
    { title: "Bakery" },
    { title: "Butcher" },
    { title: "Fish market" },
    { title: "Flower shop" },
    { title: "Garden center" },
    { title: "Pet store" },
    { title: "Gym" },
    { title: "Yoga studio" },
    { title: "Dance studio" },
    { title: "Martial arts dojo" },
    { title: "Swimming pool" },
    { title: "Tennis court" },
    { title: "Basketball court" },
    { title: "Football field" },
    { title: "Baseball field" },
    { title: "Soccer field" },
    { title: "Golf course" },
    { title: "Bowling alley" },
    { title: "Skate park" },
    { title: "Ice rink" },
    { title: "Ski resort" },
    { title: "Beach" },
    { title: "Lake" },
    { title: "River" },
    { title: "Mountain" },
    { title: "Forest" },
    { title: "Desert" },
    { title: "Island" },
    { title: "City" },
    { title: "Town" },
    { title: "Village" },
    { title: "Countryside" },
    { title: "Suburb" },
    { title: "Park" },
    { title: "Playground" },
    { title: "Garden" },
    { title: "Backyard" },
    { title: "Patio" },
    { title: "Balcony" },
    { title: "Roof" },
    { title: "Attic" },
    { title: "Basement" },
    { title: "Garage" },
    { title: "Shed" },
    { title: "Barn" },
    { title: "Greenhouse" },
    { title: "Workshop" },
    { title: "Studio" },
    { title: "Office" },
    { title: "Living room" },
    { title: "Dining room" },
    { title: "Kitchen" },
    { title: "Bedroom" },
    { title: "Bathroom" },
    { title: "Laundry room" },
    { title: "Hallway" },
    { title: "Staircase" },
    { title: "Elevator" },
    { title: "Escalator" },
    { title: "Lobby" },
    { title: "Reception" },
    { title: "Conference room" },
    { title: "Meeting room" },
    { title: "Break room" },
    { title: "Cafeteria" },
    { title: "Auditorium" },
    { title: "Gymnasium" },
    { title: "Library" },
    { title: "Laboratory" },
    { title: "Workshop" },
    { title: "Studio" },
    { title: "Gallery" },
    { title: "Exhibition" },
    { title: "Showroom" },
    { title: "Warehouse" },
    { title: "Factory" },
    { title: "Plant" },
    { title: "Mill" },
    { title: "Mine" },
    { title: "Quarry" },
    { title: "Oil rig" },
    { title: "Power plant" },
    { title: "Wind farm" },
    { title: "Solar farm" },
    { title: "Hydroelectric dam" },
    { title: "Nuclear plant" },
    { title: "Space station" },
    { title: "Satellite" },
    { title: "Rocket" },
    { title: "Spaceship" },
    { title: "Submarine" },
    { title: "Aircraft carrier" },
    { title: "Battleship" },
    { title: "Cruise ship" },
    { title: "Ferry" },
    { title: "Yacht" },
    { title: "Sailboat" },
    { title: "Speedboat" },
    { title: "Canoe" },
    { title: "Kayak" },
    { title: "Rowboat" },
    { title: "Raft" },
    { title: "Jet ski" },
    { title: "Water scooter" },
    { title: "Hovercraft" },
    { title: "Seaplane" },
    { title: "Helicopter" },
    { title: "Glider" },
    { title: "Hot air balloon" },
    { title: "Blimp" },
    { title: "Zeppelin" },
    { title: "Parachute" },
    { title: "Hang glider" },
    { title: "Wingsuit" },
    { title: "Jetpack" },
    { title: "Spacesuit" },
    { title: "Diving suit" },
    { title: "Wetsuit" },
    { title: "Dry suit" },
    { title: "Life jacket" },
    { title: "Helmet" },
    { title: "Goggles" },
    { title: "Gloves" },
    { title: "Boots" },
    { title: "Shoes" },
    { title: "Sandals" },
    { title: "Slippers" },
    { title: "Socks" },
    { title: "Hat" },
    { title: "Cap" },
    { title: "Beanie" },
    { title: "Scarf" },
    { title: "Belt" },
    { title: "Tie" },
    { title: "Bow tie" },
    { title: "Suspenders" },
    { title: "Watch" },
    { title: "Bracelet" },
    { title: "Necklace" },
    { title: "Earrings" },
    { title: "Ring" },
    { title: "Brooch" },
    { title: "Cufflinks" },
    { title: "Pocket square" },
    { title: "Handkerchief" },
    { title: "Wallet" },
    { title: "Purse" },
    { title: "Backpack" },
    { title: "Suitcase" },
    { title: "Briefcase" },
    { title: "Laptop bag" },
    { title: "Messenger bag" },
    { title: "Tote bag" },
    { title: "Gym bag" },
    { title: "Duffel bag" },
    { title: "Camera bag" },
    { title: "Diaper bag" },
    { title: "Cooler" },
    { title: "Lunchbox" },
    { title: "Thermos" },
    { title: "Water bottle" },
    { title: "Flask" },
    { title: "Mug" },
    { title: "Cup" },
    { title: "Glass" },
    { title: "Plate" },
    { title: "Bowl" },
    { title: "Fork" },
    { title: "Knife" },
    { title: "Spoon" },
    { title: "Chopsticks" },
    { title: "Napkin" },
    { title: "Tablecloth" },
    { title: "Placemat" },
    { title: "Coaster" },
    { title: "Candle" },
    { title: "Lamp" },
    { title: "Light bulb" },
    { title: "Flashlight" },
    { title: "Lantern" },
    { title: "Torch" },
    { title: "Fireplace" },
    { title: "Stove" },
    { title: "Oven" },
    { title: "Microwave" },
    { title: "Toaster" },
    { title: "Blender" },
    { title: "Mixer" },
    { title: "Coffee maker" },
    { title: "Tea kettle" },
    { title: "Refrigerator" },
    { title: "Freezer" },
    { title: "Dishwasher" },
    { title: "Washing machine" },
    { title: "Dryer" },
    { title: "Iron" },
    { title: "Vacuum cleaner" },
    { title: "Broom" },
    { title: "Mop" },
    { title: "Dustpan" },
    { title: "Bucket" },
    { title: "Sponge" },
    { title: "Scrub brush" },
    { title: "Toilet brush" },
    { title: "Plunger" },
    { title: "Trash can" },
    { title: "Recycling bin" },
    { title: "Compost bin" },
    { title: "Lawn mower" },
    { title: "Leaf blower" },
    { title: "Hedge trimmer" },
    { title: "Chainsaw" },
    { title: "Weed whacker" },
    { title: "Garden hose" },
    { title: "Sprinkler" },
    { title: "Watering can" },
    { title: "Rake" },
    { title: "Shovel" },
    { title: "Hoe" },
    { title: "Trowel" },
    { title: "Pruning shears" },
    { title: "Loppers" },
    { title: "Wheelbarrow" },
    { title: "Garden cart" },
    { title: "Compost bin" },
    { title: "Rain barrel" },
    { title: "Bird feeder" },
    { title: "Birdhouse" },
    { title: "Birdbath" },
    { title: "Sundial" },
    { title: "Wind chimes" },
    { title: "Garden gnome" },
    { title: "Statue" },
    { title: "Fountain" },
    { title: "Pond" },
    { title: "Waterfall" },
    { title: "Rock garden" },
    { title: "Zen garden" },
    { title: "Flower bed" },
    { title: "Vegetable garden" },
    { title: "Herb garden" },
    { title: "Fruit orchard" },
    { title: "Vineyard" },
    { title: "Greenhouse" },
    { title: "Potting shed" },
    { title: "Tool shed" },
    { title: "Workshop" },
    { title: "Garage" },
    { title: "Carport" },
    { title: "Driveway" },
    { title: "Sidewalk" },
    { title: "Pathway" },
    { title: "Fence" },
    { title: "Gate" },
    { title: "Wall" },
    { title: "Hedge" },
    { title: "Tree" },
    { title: "Shrub" },
    { title: "Bush" },
    { title: "Vine" },
    { title: "Grass" },
    { title: "Flower" },
    { title: "Plant" },
    { title: "Treehouse" },
    { title: "Playhouse" },
    { title: "Sandbox" },
    { title: "Swing set" },
    { title: "Slide" },
    { title: "Seesaw" },
    { title: "Monkey bars" },
    { title: "Climbing wall" },
    { title: "Trampoline" },
    { title: "Bounce house" },
    { title: "Water slide" },
    { title: "Sprinkler" },
    { title: "Pool" },
    { title: "Hot tub" },
    { title: "Sauna" },
    { title: "Steam room" },
    { title: "Outdoor shower" },
    { title: "Fire pit" },
    { title: "Barbecue grill" },
    { title: "Picnic table" },
    { title: "Patio furniture" },
    { title: "Hammock" },
    { title: "Lawn chair" },
    { title: "Deck chair" },
    { title: "Beach chair" },
    { title: "Umbrella" },
  ],
};

export default deck;
