import { ExampleDeck } from "./types";
import front, { dataIds } from "@/constants/builtInTemplates/front";
import back, {
  dataIds as backDataIds,
} from "@/constants/builtInTemplates/back";

const deck: ExampleDeck<{ title: string; emoji?: string }> = {
  name: "Emojis! 🤡👍🐶",
  devOnly: false,
  description:
    "All the emojis! Use these cards to play charades, pictionary, or any other game that needs a random emoji!",
  templates: {
    back: {
      templateId: back.templateId,
      dataTemplateMapping: {
        [backDataIds.text]: {
          dataId: "backText",
          templateDataId: backDataIds.text,
        },
        [backDataIds.emoji]: {
          dataId: "backEmoji",
          templateDataId: backDataIds.emoji,
        },
        [backDataIds.color]: {
          dataId: "color",
          templateDataId: backDataIds.color,
        },
      },
    },
    front: {
      dataTemplateMapping: {
        [dataIds.title]: {
          dataId: "title",
          templateDataId: dataIds.title,
        },
        [dataIds.description]: {
          dataId: "description",
          templateDataId: dataIds.description,
        },
        [dataIds.emoji]: {
          dataId: "emoji",
          templateDataId: dataIds.emoji,
        },
        [dataIds.color]: {
          dataId: "color",
          templateDataId: dataIds.color,
        },
      },
      templateId: front.templateId,
    },
  },
  dataSchema: {
    backEmoji: {
      id: "backEmoji",
      type: "text",
      defaultValidatedValue: {
        type: "text",
        value: "🤡👍",
      },
    },
    backText: {
      id: "backText",
      type: "text",
      defaultValidatedValue: {
        type: "text",
        value: "Emojis!",
      },
    },
    title: {
      id: "title",
      type: "text",
    },
    emoji: {
      id: "emoji",
      type: "text",
    },
    description: {
      id: "description",
      type: "text",
      defaultValidatedValue: {
        type: "null",
        value: null,
      },
    },
    color: {
      id: "color",
      type: "color",
      defaultValidatedValue: {
        type: "color",
        value: "#F2358D",
      },
    },
  },
  cards: [
    { emoji: "🤡", title: "Clown" },
    { emoji: "👍", title: "Thumbs Up" },
    { emoji: "🐶", title: "Dog" },
    { emoji: "🚀", title: "Rocket" },
    { emoji: "🌟", title: "Star" },
    { emoji: "🍕", title: "Pizza" },
    { emoji: "🎸", title: "Guitar" },
    { emoji: "🏖️", title: "Beach" },
    { emoji: "🐉", title: "Dragon" },
    { emoji: "🦄", title: "Unicorn" },
    { emoji: "🎨", title: "Palette" },
    { emoji: "📚", title: "Books" },
    { emoji: "🎲", title: "Dice" },
    { emoji: "🧩", title: "Puzzle" },
    { emoji: "🎯", title: "Target" },
    { emoji: "🛸", title: "UFO" },
    { emoji: "🌈", title: "Rainbow" },
    { emoji: "🔥", title: "Fire" },
    { emoji: "💡", title: "Light Bulb" },
    { emoji: "⚡", title: "Lightning" },
    { emoji: "🌍", title: "Earth" },
    { emoji: "🦁", title: "Lion" },
    { emoji: "🐘", title: "Elephant" },
    { emoji: "🐳", title: "Whale" },
    { emoji: "🦜", title: "Parrot" },
    { emoji: "🍎", title: "Apple" },
    { emoji: "🍩", title: "Donut" },
    { emoji: "🍔", title: "Burger" },
    { emoji: "🍣", title: "Sushi" },
    { emoji: "🥑", title: "Avocado" },
    { emoji: "🌮", title: "Taco" },
    { emoji: "🥨", title: "Pretzel" },
    { emoji: "🍿", title: "Popcorn" },
    { emoji: "🎃", title: "Pumpkin" },
    { emoji: "🎁", title: "Gift" },
    { emoji: "🎈", title: "Balloon" },
    { emoji: "🎉", title: "Party" },
    { emoji: "🎵", title: "Music Note" },
    { emoji: "🎻", title: "Violin" },
    { emoji: "🥁", title: "Drum" },
    { emoji: "🎤", title: "Microphone" },
    { emoji: "🎧", title: "Headphones" },
    { emoji: "🏆", title: "Trophy" },
    { emoji: "⚽", title: "Soccer Ball" },
    { emoji: "🏀", title: "Basketball" },
    { emoji: "🏈", title: "Football" },
    { emoji: "🎳", title: "Bowling" },
    { emoji: "🏓", title: "Ping Pong" },
    { emoji: "🛹", title: "Skateboard" },
    { emoji: "🚴", title: "Cyclist" },
    { emoji: "🏇", title: "Horse Racing" },
    { emoji: "🏂", title: "Snowboarder" },
    { emoji: "🧗", title: "Climber" },
    { emoji: "🚣", title: "Rowboat" },
    { emoji: "🏕️", title: "Camping" },
    { emoji: "🗻", title: "Mountain" },
    { emoji: "🏞️", title: "National Park" },
    { emoji: "🌋", title: "Volcano" },
    { emoji: "🏰", title: "Castle" },
    { emoji: "🗽", title: "Statue of Liberty" },
    { emoji: "🗿", title: "Moai" },
    { emoji: "🚂", title: "Train" },
    { emoji: "✈️", title: "Airplane" },
    { emoji: "🚢", title: "Ship" },
    { emoji: "🚗", title: "Car" },
    { emoji: "🚕", title: "Taxi" },
    { emoji: "🚑", title: "Ambulance" },
    { emoji: "🚒", title: "Fire Truck" },
    { emoji: "🚓", title: "Police Car" },
    { emoji: "🚜", title: "Tractor" },
    { emoji: "🛵", title: "Scooter" },
    { emoji: "🚲", title: "Bicycle" },
    { emoji: "🛶", title: "Canoe" },
    { emoji: "⛵", title: "Sailboat" },
    { emoji: "🛳️", title: "Cruise Ship" },
    { emoji: "🚁", title: "Helicopter" },
    { emoji: "🛰️", title: "Satellite" },
    { emoji: "🛸", title: "Flying Saucer" },
    { emoji: "🌌", title: "Milky Way" },
    { emoji: "🌠", title: "Shooting Star" },
    { emoji: "🌞", title: "Sun with Face" },
    { emoji: "🌜", title: "Moon with Face" },
    { emoji: "🌛", title: "First Quarter Moon" },
    { emoji: "🌚", title: "New Moon Face" },
    { emoji: "🌝", title: "Full Moon Face" },
    { emoji: "🌅", title: "Sunrise" },
    { emoji: "🌄", title: "Sunrise Over Mountains" },
    { emoji: "🌇", title: "Sunset" },
    { emoji: "🌃", title: "Night with Stars" },
    { emoji: "🌉", title: "Bridge at Night" },
    { emoji: "🌁", title: "Foggy" },
    { emoji: "🌬️", title: "Wind Face" },
    { emoji: "🌪️", title: "Tornado" },
    { emoji: "🌈", title: "Rainbow" },
    { emoji: "☀️", title: "Sun" },
    { emoji: "☁️", title: "Cloud" },
    { emoji: "⛅", title: "Partly Cloudy" },
    { emoji: "🌧️", title: "Rain Cloud" },
    { emoji: "⛈️", title: "Thunderstorm" },
    { emoji: "🌩️", title: "Lightning Cloud" },
    { emoji: "🌨️", title: "Snow Cloud" },
    { emoji: "❄️", title: "Snowflake" },
    { emoji: "☃️", title: "Snowman" },
    { emoji: "⛄", title: "Snowman Without Snow" },
    { emoji: "🌊", title: "Wave" },
    { emoji: "💧", title: "Droplet" },
    { emoji: "🌫️", title: "Fog" },
    { emoji: "🌿", title: "Herb" },
    { emoji: "🍀", title: "Four Leaf Clover" },
    { emoji: "🍁", title: "Maple Leaf" },
    { emoji: "🍂", title: "Fallen Leaf" },
    { emoji: "🍃", title: "Leaf Fluttering in Wind" },
    { emoji: "🌾", title: "Sheaf of Rice" },
    { emoji: "🌵", title: "Cactus" },
    { emoji: "🎄", title: "Christmas Tree" },
    { emoji: "🌲", title: "Evergreen Tree" },
    { emoji: "🌳", title: "Deciduous Tree" },
    { emoji: "🌴", title: "Palm Tree" },
    { emoji: "🌱", title: "Seedling" },
    { emoji: "🌺", title: "Hibiscus" },
    { emoji: "🌸", title: "Cherry Blossom" },
    { emoji: "🌼", title: "Blossom" },
    { emoji: "🌻", title: "Sunflower" },
    { emoji: "🌹", title: "Rose" },
    { emoji: "🥀", title: "Wilted Flower" },
    { emoji: "💐", title: "Bouquet" },
    { emoji: "🌷", title: "Tulip" },
    { emoji: "🌾", title: "Wheat" },
    { emoji: "🌿", title: "Herb" },
    { emoji: "🍄", title: "Mushroom" },
    { emoji: "🌰", title: "Chestnut" },
    { emoji: "🦀", title: "Crab" },
    { emoji: "🦞", title: "Lobster" },
    { emoji: "🦐", title: "Shrimp" },
    { emoji: "🦑", title: "Squid" },
    { emoji: "🐙", title: "Octopus" },
    { emoji: "🐡", title: "Blowfish" },
    { emoji: "🐠", title: "Tropical Fish" },
    { emoji: "🐟", title: "Fish" },
    { emoji: "🐬", title: "Dolphin" },
    { emoji: "🐳", title: "Whale" },
    { emoji: "🐋", title: "Blue Whale" },
    { emoji: "🦈", title: "Shark" },
    { emoji: "🐊", title: "Crocodile" },
    { emoji: "🐢", title: "Turtle" },
    { emoji: "🦎", title: "Lizard" },
    { emoji: "🐍", title: "Snake" },
    { emoji: "🐉", title: "Dragon" },
    { emoji: "🦕", title: "Sauropod" },
    { emoji: "🦖", title: "T-Rex" },
    { emoji: "🐎", title: "Horse" },
    { emoji: "🦓", title: "Zebra" },
    { emoji: "🦌", title: "Deer" },
    { emoji: "🐂", title: "Ox" },
    { emoji: "🐃", title: "Water Buffalo" },
    { emoji: "🐄", title: "Cow" },
    { emoji: "🐖", title: "Pig" },
    { emoji: "🐏", title: "Ram" },
    { emoji: "🐑", title: "Sheep" },
    { emoji: "🐐", title: "Goat" },
    { emoji: "🦙", title: "Llama" },
    { emoji: "🦒", title: "Giraffe" },
    { emoji: "🐘", title: "Elephant" },
    { emoji: "🦏", title: "Rhinoceros" },
    { emoji: "🦛", title: "Hippopotamus" },
    { emoji: "🐁", title: "Mouse" },
    { emoji: "🐀", title: "Rat" },
    { emoji: "🐹", title: "Hamster" },
    { emoji: "🐰", title: "Rabbit" },
    { emoji: "🐇", title: "Bunny" },
    { emoji: "🦝", title: "Raccoon" },
    { emoji: "🐻", title: "Bear" },
    { emoji: "🐨", title: "Koala" },
    { emoji: "🐼", title: "Panda" },
    { emoji: "🦘", title: "Kangaroo" },
    { emoji: "🦡", title: "Badger" },
    { emoji: "🐾", title: "Paw Prints" },
    { emoji: "🐉", title: "Dragon" },
    { emoji: "🦄", title: "Unicorn" },
    { emoji: "🦋", title: "Butterfly" },
    { emoji: "🐌", title: "Snail" },
    { emoji: "🐛", title: "Bug" },
    { emoji: "🐜", title: "Ant" },
    { emoji: "🐝", title: "Bee" },
    { emoji: "🪲", title: "Beetle" },
    { emoji: "🐞", title: "Ladybug" },
    { emoji: "🦗", title: "Cricket" },
    { emoji: "🕷️", title: "Spider" },
    { emoji: "🕸️", title: "Spider Web" },
    { emoji: "🦂", title: "Scorpion" },
    { emoji: "🦟", title: "Mosquito" },
    { emoji: "🦠", title: "Microbe" },
    { emoji: "🦦", title: "Otter" },
    { emoji: "🦥", title: "Sloth" },
    { emoji: "🦨", title: "Skunk" },
    { emoji: "🦩", title: "Flamingo" },
    { emoji: "🦚", title: "Peacock" },
    { emoji: "🦜", title: "Parrot" },
    { emoji: "🦢", title: "Swan" },
    { emoji: "🦩", title: "Flamingo" },
    { emoji: "🦉", title: "Owl" },
    { emoji: "🦇", title: "Bat" },
    { emoji: "🐺", title: "Wolf" },
    { emoji: "🦊", title: "Fox" },
    { emoji: "🐗", title: "Boar" },
    { emoji: "🐴", title: "Horse Face" },
    { emoji: "🦄", title: "Unicorn Face" },
    { emoji: "🐝", title: "Honeybee" },
    { emoji: "🐛", title: "Bug" },
    { emoji: "🦋", title: "Butterfly" },
    { emoji: "🐌", title: "Snail" },
    { emoji: "🐞", title: "Lady Beetle" },
    { emoji: "🐜", title: "Ant" },
    { emoji: "🪲", title: "Beetle" },
    { emoji: "🦗", title: "Cricket" },
    { emoji: "🕷️", title: "Spider" },
    { emoji: "🕸️", title: "Spider Web" },
    { emoji: "🦂", title: "Scorpion" },
    { emoji: "🦟", title: "Mosquito" },
    { emoji: "🦠", title: "Microbe" },
    { emoji: "🌵", title: "Cactus" },
    { emoji: "🎄", title: "Christmas Tree" },
    { emoji: "🌲", title: "Evergreen Tree" },
    { emoji: "🌳", title: "Deciduous Tree" },
    { emoji: "🌴", title: "Palm Tree" },
    { emoji: "🌱", title: "Seedling" },
    { emoji: "🌿", title: "Herb" },
    { emoji: "☘️", title: "Shamrock" },
    { emoji: "🍀", title: "Four Leaf Clover" },
    { emoji: "🍁", title: "Maple Leaf" },
    { emoji: "🍂", title: "Fallen Leaf" },
    { emoji: "🍃", title: "Leaf Fluttering in Wind" },
    { emoji: "🌾", title: "Sheaf of Rice" },
    { emoji: "🌺", title: "Hibiscus" },
    { emoji: "🌸", title: "Cherry Blossom" },
    { emoji: "🌼", title: "Blossom" },
    { emoji: "🌻", title: "Sunflower" },
    { emoji: "🌹", title: "Rose" },
    { emoji: "🥀", title: "Wilted Flower" },
    { emoji: "💐", title: "Bouquet" },
    { emoji: "🌷", title: "Tulip" },
    { emoji: "🌾", title: "Wheat" },
    { emoji: "🍄", title: "Mushroom" },
    { emoji: "🌰", title: "Chestnut" },
    { emoji: "🦀", title: "Crab" },
    { emoji: "🦞", title: "Lobster" },
    { emoji: "🦐", title: "Shrimp" },
    { emoji: "🦑", title: "Squid" },
    { emoji: "🐙", title: "Octopus" },
    { emoji: "🐡", title: "Blowfish" },
    { emoji: "🐠", title: "Tropical Fish" },
    { emoji: "🐟", title: "Fish" },
    { emoji: "🐬", title: "Dolphin" },
    { emoji: "🐳", title: "Whale" },
    { emoji: "🐋", title: "Blue Whale" },
    { emoji: "🦈", title: "Shark" },
    { emoji: "🐊", title: "Crocodile" },
    { emoji: "🐢", title: "Turtle" },
    { emoji: "🦎", title: "Lizard" },
    { emoji: "🐍", title: "Snake" },
    { emoji: "🐉", title: "Dragon" },
    { emoji: "🦕", title: "Sauropod" },
    { emoji: "🦖", title: "T-Rex" },
    { emoji: "🐎", title: "Horse" },
    { emoji: "🦓", title: "Zebra" },
    { emoji: "🦌", title: "Deer" },
    { emoji: "🐂", title: "Ox" },
    { emoji: "🐃", title: "Water Buffalo" },
    { emoji: "🐄", title: "Cow" },
    { emoji: "🐖", title: "Pig" },
    { emoji: "🐏", title: "Ram" },
    { emoji: "🐑", title: "Sheep" },
    { emoji: "🐐", title: "Goat" },
    { emoji: "🦙", title: "Llama" },
    { emoji: "🦒", title: "Giraffe" },
    { emoji: "🐘", title: "Elephant" },
    { emoji: "🦏", title: "Rhinoceros" },
    { emoji: "🦛", title: "Hippopotamus" },
    { emoji: "🐁", title: "Mouse" },
    { emoji: "🐀", title: "Rat" },
    { emoji: "🐹", title: "Hamster" },
    { emoji: "🐰", title: "Rabbit" },
    { emoji: "🐇", title: "Bunny" },
    { emoji: "🦝", title: "Raccoon" },
    { emoji: "🐻", title: "Bear" },
    { emoji: "🐨", title: "Koala" },
    { emoji: "🐼", title: "Panda" },
    { emoji: "🦘", title: "Kangaroo" },
    { emoji: "🦡", title: "Badger" },
    { emoji: "🐾", title: "Paw Prints" },
  ],
};

export default deck;
